import { generateQuestion, generateUniqueQuestion, questionFingerprint, generateReviewQuestion, isCorrect, nextDifficulty, rageLevel, quizGrade, resultLabel, SUBJECT_KEYS } from './engine.js';
import { nonsense, subjectNonsense, glorpLines, cosmetics, subjects, subjectMeta } from './content.js';
import { AudioDirector } from './audio.js';
import { ensureProgressState, recordProgressAnswer, recordSession, progressSnapshot, skillWeaknesses, recommendedSkills, masteryRecords, progressBand } from './progress.js';
import { chooseAdaptiveDescriptor, adaptiveDifficultyFor } from './adaptive.js';
import { masteryBand } from './mastery.js';
import { gameplaySetting, earnedActivityLayers, activityProgressName } from './gameplay-settings.js';
import { renderInteraction } from './interactions.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const screens=$$('.screen');
const defaultState={grade:3,sessionLength:10,skill:'mixed',sound:true,voice:true,music:true,haptics:true,largeText:false,rounds:0,wins:0,lifetimeCorrect:0,equipped:'none',selectedSubject:'mixed',enabledSubjects:[...SUBJECT_KEYS],quizzes:0,reviews:0,masteryPractices:0,subjectStats:{},gradeStats:{},skillStats:{},masteryStats:{},dailyStats:{},sessionHistory:[],progressSchemaVersion:3};
function readStored(key){try{return JSON.parse(localStorage.getItem(key)||'null');}catch{return null;}}
const legacyMath=readStored('brainrotMathPrefs');
const legacyEducation=readStored('brainrotEducationPrefs');
const academyPrimary=readStored('brainrotAcademyPrefs');
const academyBackup=readStored('brainrotAcademyPrefsBackup');
const academySaved=academyPrimary||academyBackup;
let prefs={...defaultState,...(legacyMath||{}),...(legacyEducation||{}),...(academySaved||{})};
if(!Array.isArray(prefs.enabledSubjects)||!prefs.enabledSubjects.length)prefs.enabledSubjects=[...SUBJECT_KEYS];
ensureProgressState(prefs);
let game=null,paused=false,pendingMode='battle',pendingGameplay='battle',review=null,lastQuizMisses=[];
const audio=new AudioDirector(()=>prefs);

const battleAssetUrls=['./assets/scenes/glorp-room-v05.webp','./assets/scenes/professor-study-v05.webp','./assets/scenes/pizza-kitchen-premium.svg','./assets/scenes/milkshake-lab-premium.svg','./assets/scenes/activity-hall-premium.svg','./assets/ui/modes/brain-battle.svg','./assets/ui/modes/pizza-party.svg','./assets/ui/modes/milkshake.svg','./assets/rig/base.webp','./assets/rig/eye-left.webp','./assets/rig/eye-right.webp','./assets/rig/mouth.webp','./assets/rig/phone.webp','./assets/rig/gesture-point.svg','./assets/rig/gesture-fist.svg','./assets/rig/prof-hand-pointer.svg'];
battleAssetUrls.forEach(src=>{const im=new Image();im.decoding='async';im.src=src;});
function save(){try{const current=localStorage.getItem('brainrotAcademyPrefs');if(current){try{JSON.parse(current);localStorage.setItem('brainrotAcademyPrefsBackup',current);}catch{}}localStorage.setItem('brainrotAcademyPrefs',JSON.stringify(prefs));}catch{}}
function haptic(pattern){if(!prefs.haptics||!('vibrate' in navigator))return;try{navigator.vibrate(pattern);}catch{}}
function applyAccessibilityPrefs(){document.documentElement.classList.toggle('large-text',!!prefs.largeText);}
function syncDock(id){const map={homeScreen:'navHomeBtn',activityScreen:'navPlayBtn',subjectScreen:pendingMode==='quiz'?'navQuizBtn':'navPlayBtn',gradeScreen:'navHomeBtn',closetScreen:'navClosetBtn',parentScreen:'navParentBtn'};$$('.dock-item').forEach(b=>b.classList.toggle('active',b.id===map[id]));}
function show(id){const prev=document.body.dataset.screen;if(prev&&prev!==id&&id!=='battleScreen')audio.sfx('whoosh',.18);screens.forEach(s=>s.classList.toggle('active',s.id===id));document.body.dataset.screen=id;syncDock(id);const active=$(`#${id}`);if(active){active.scrollTop=0;active.classList.remove('screen-enter');void active.offsetWidth;active.classList.add('screen-enter');setTimeout(()=>active.classList.remove('screen-enter'),420);}}
function showToast(text){const t=$('#appToast');if(!t)return;t.textContent=text;t.classList.remove('show');void t.offsetWidth;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300);}
function ordinal(n){return['','1st','2nd','3rd','4th','5th','6th'][n]||`${n}th`;}
const recentLines=[];
const professorHomeLines=['Ready for a brain battle?','Pick a challenge and show Glorp what you know.','Correct answers make Glorp dramatically upset.','Class is in session. Glorp is already complaining.','Choose your grade, scholar. We have a blob to defeat.'];
function random(arr){const available=arr.filter(x=>!recentLines.includes(x));const pool=available.length?available:arr;const value=pool[Math.floor(Math.random()*pool.length)];recentLines.push(value);if(recentLines.length>4)recentLines.shift();return value;}
function setBubble(text){$('#glorpBubble').textContent=text;}
function say(text,fallback='growl'){$('#glorpBubble')?.classList.remove('hidden');setBubble(text);audio.voice(text,fallback);const stage=$('#glorpStage'),rig=$('#glorpRig');stage?.classList.remove('talking');rig?.classList.remove('rig-talking');if(stage)void stage.offsetWidth;stage?.classList.add('talking');rig?.classList.add('rig-talking');const duration=Math.min(1900,650+text.length*27);setTimeout(()=>{stage?.classList.remove('talking');rig?.classList.remove('rig-talking');},duration);}
function professorSay(text,fallback='chalk'){const bubble=$('#professorBubble'),rig=document.querySelector('.professor-rig');if(bubble)bubble.textContent=text;if(fallback)audio.sfx(fallback,.28);rig?.classList.remove('prof-talking');if(rig)void rig.offsetWidth;rig?.classList.add('prof-talking');const duration=Math.min(2600,750+text.length*30);setTimeout(()=>rig?.classList.remove('prof-talking'),duration);}
function professorBattleSay(text,state='prompt'){const host=$('#professorBattleHost'),bubble=$('#professorBattleBubble');if(!host||!bubble)return;host.classList.remove('hidden','good','bad','prompt','pop');host.classList.add(state);bubble.textContent=text;void host.offsetWidth;host.classList.add('pop');setTimeout(()=>host.classList.remove('pop'),520);}
const professorHostedSubjects=new Set(['spelling','grammar','math','reading']);
function professorHostsQuestion(q){return professorHostedSubjects.has(q?.subject);}
function setProfessorBattleMode(q){const host=$('#professorBattleHost');if(!host)return;const hosted=professorHostsQuestion(q);host.classList.toggle('hidden',!hosted);host.classList.remove('good','bad','prompt','pop');if(hosted){professorBattleSay(q.prompt,'prompt');audio.sfx('chalk',.2);}}

const rigReactionClasses=['rig-hit-a','rig-hit-b','rig-hit-c','rig-laugh-a','rig-laugh-b','rig-laugh-c','rig-rage-surge','rig-meltdown'];
const rigPoseClasses=['rig-pose-point','rig-pose-fist','rig-pose-shock','rig-pose-smug','rig-pose-head'];
const lookChoiceClasses=['look-choice-0','look-choice-1','look-choice-2','look-choice-3'];
function clearRigPose(){const rig=$('#glorpRig');if(!rig)return;rigPoseClasses.forEach(c=>rig.classList.remove(c));}
function performRigPose(pose,duration=820){const rig=$('#glorpRig');if(!rig)return;clearRigPose();const cls='rig-pose-'+pose;rig.classList.add(cls);setTimeout(()=>rig.classList.remove(cls),duration);}
function lookAtChoice(index){const rig=$('#glorpRig');if(!rig)return;lookChoiceClasses.forEach(c=>rig.classList.remove(c));if(Number.isInteger(index)){rig.classList.add(`look-choice-${index}`);setTimeout(()=>lookChoiceClasses.forEach(c=>rig.classList.remove(c)),520);}}
function rigReaction(kind){const rig=$('#glorpRig');if(!rig)return;rigReactionClasses.forEach(c=>rig.classList.remove(c));void rig.offsetWidth;let cls='';if(kind==='correct')cls=['rig-hit-a','rig-hit-b','rig-hit-c'][Math.floor(Math.random()*3)];else if(kind==='wrong')cls=['rig-laugh-a','rig-laugh-b','rig-laugh-c'][Math.floor(Math.random()*3)];else if(kind==='rage')cls='rig-rage-surge';else if(kind==='meltdown')cls='rig-meltdown';if(cls){rig.classList.add(cls);setTimeout(()=>rig.classList.remove(cls),kind==='meltdown'?1500:850);}}
function blinkGlorp(){const rig=$('#glorpRig');if(!rig||paused||document.body.dataset.screen!=='battleScreen')return;rig.classList.add('rig-blink');setTimeout(()=>rig.classList.remove('rig-blink'),180);}
setInterval(()=>{if(Math.random()<.74)blinkGlorp();},2600);
function screenFlash(kind='good'){const f=$('#screenFlash');f.className=`screen-flash ${kind}`;void f.offsetWidth;f.classList.add('go');setTimeout(()=>f.className='screen-flash',430);}
function reactionGlyph(text,kind='angry'){const el=$('#reactionGlyph');el.textContent=text;el.className=`reaction-glyph ${kind}`;void el.offsetWidth;el.classList.add('pop');setTimeout(()=>el.className='reaction-glyph',760);}
function burst(type='slime',count=10){const layer=$('#particleLayer');if(!layer)return;for(let i=0;i<count;i++){const p=document.createElement('i');p.className=`particle ${type}`;const angle=(-150+Math.random()*120)*Math.PI/180,dist=45+Math.random()*120;p.style.setProperty('--dx',`${Math.cos(angle)*dist}px`);p.style.setProperty('--dy',`${Math.sin(angle)*dist}px`);p.style.setProperty('--r',`${Math.random()*220-110}deg`);p.style.setProperty('--s',`${.5+Math.random()*1.1}`);p.style.left=`${38+Math.random()*25}%`;p.style.top=`${54+Math.random()*20}%`;layer.appendChild(p);setTimeout(()=>p.remove(),900);}}
function stageImpact(kind){const stage=$('#glorpStage');stage.classList.remove('impact-correct','impact-wrong','rage-level-up');void stage.offsetWidth;stage.classList.add(kind==='correct'?'impact-correct':'impact-wrong');rigReaction(kind);setTimeout(()=>stage.classList.remove('impact-correct','impact-wrong'),720);}
function levelUpRage(level){const stage=$('#glorpStage');performRigPose(level>=3?'head':'fist',920);stage.classList.remove('rage-level-up');void stage.offsetWidth;stage.classList.add('rage-level-up');audio.sfx('rage',.9);haptic(level>=3?[35,28,45]:28);if(level>=2)audio.sfx('growl',.55);reactionGlyph(['','HEY!','GRR!','NOOO!','SPLORP!'][level]||'GRR!','angry');burst(level>=3?'ember':'slime',8+level*3);rigReaction('rage');setTimeout(()=>stage.classList.remove('rage-level-up'),850);}

function updateHome(){const grade=`${ordinal(prefs.grade)} Grade`;$('#homeGradeLabel').textContent=grade;$('#homeGradeStatus').textContent=grade;$('#homeBubble').textContent=random(professorHomeLines);}
function openGameplayPicker(){pendingMode='battle';show('activityScreen');}
function launchGameplaySetting(id){const setting=gameplaySetting(id);pendingGameplay=setting.id;if(setting.id==='battle'){openSubjectPicker('battle');return;}prefs.selectedSubject=setting.subject;save();startSession('battle',setting.subject,{setting:setting.id,label:setting.shortLabel});}
function openSubjectPicker(mode){pendingMode=mode;if(mode==='quiz')pendingGameplay='battle';$('#subjectTitle').textContent=mode==='quiz'?'CHOOSE YOUR QUIZ':'CHOOSE YOUR CHALLENGE';$('#subjectModeCopy').textContent=mode==='quiz'?'Pick one subject or take a mixed grade-level quiz.':'Pick one subject or mix them all together.';renderSubjects();show('subjectScreen');}
function renderSubjects(){const grid=$('#subjectGrid');grid.innerHTML='';subjects.forEach(s=>{const b=document.createElement('button');b.className=`subject-card ${s.id==='mixed'?'featured':''} ${s.featured?'core-game':''}`;b.dataset.subject=s.id;const branded=pendingMode==='battle'&&s.challengeName,title=branded?s.challengeName:s.name,description=branded?(s.challengeDescription||s.description):s.description,tag=branded&&s.challengeTag?`<em class="subject-mode-tag">${s.challengeTag}</em>`:'';b.innerHTML=`<span class="subject-icon"><img src="${s.art}" alt=""></span><span class="subject-copy">${tag}<b>${title}</b><small>${description}</small></span><span class="subject-arrow" aria-hidden="true">›</span>`;b.addEventListener('click',()=>{prefs.selectedSubject=s.id;save();startSession(pendingMode,s.id,{setting:pendingMode==='quiz'?'battle':pendingGameplay});});grid.appendChild(b);});}
function startSession(mode='battle',subject=prefs.selectedSubject||'mixed',options={}){const length=options.length||prefs.sessionLength,setting=mode==='quiz'?'battle':(options.setting||pendingGameplay||'battle');game={mode,subject,setting,index:0,score:0,streak:0,bestStreak:0,ragePoints:0,difficulty:1,recent:[],locked:false,questions:[],usedFingerprints:new Set(),missed:[],lastRageLevel:0,length,focusDescriptors:options.focusDescriptors||null,subjectScores:{},adaptivePicks:0,sessionLabel:options.label||null};show('battleScreen');const meta=subjectMeta(subject),settingMeta=gameplaySetting(setting);$('#modeLabel').textContent=options.label||(mode==='quiz'?'QUIZ':(settingMeta.id!=='battle'?settingMeta.shortLabel:(meta.shortLabel||'BATTLE')));setupGameplayStage();audio.sfx('whoosh',.34);setTimeout(()=>audio.sfx('ping',.42),120);audio.startMusic('battle');renderNext();}
function pickFocusedDescriptor(){if(!game.focusDescriptors?.length)return null;return game.focusDescriptors[game.index%game.focusDescriptors.length];}
function setupGameplayStage(){const prop=$('#activityProp'),setting=gameplaySetting(game?.setting),stage=$('#glorpStage'),panel=$('.quiz-panel');const food=setting.id==='pizza'||setting.id==='milkshake';document.body.dataset.gameplay=setting.id;stage?.setAttribute('data-gameplay',setting.id);panel?.setAttribute('data-gameplay',setting.id);const sign=$('#modeSceneSign');if(sign){const copy=setting.id==='pizza'?['MATH KITCHEN','PIZZA PARTY']:setting.id==='milkshake'?['SPELLING SHOP','SHAKE LAB']:['ACADEMY ARENA','BRAIN BATTLE'];sign.innerHTML=`<small>${copy[0]}</small><b>${copy[1]}</b>`;}const meterIcon=$('#activityMeterTitle img');if(meterIcon)meterIcon.src=setting.id==='pizza'?'assets/ui/modes/pizza-party.svg':setting.id==='milkshake'?'assets/ui/modes/milkshake.svg':'assets/ui/nav/rage.svg';if(prop){prop.classList.toggle('hidden',!food);prop.dataset.setting=food?setting.id:'';prop.classList.remove('food-pop','eating');}updateActivityProp();}
function updateActivityProp(pop=false){if(!game)return;const setting=gameplaySetting(game.setting),prop=$('#activityProp');if(!prop)return;const earned=earnedActivityLayers(setting.id,game.score,game.length);prop.querySelectorAll('[data-food-layer]').forEach(el=>el.classList.toggle('earned',Number(el.dataset.foodLayer)<=earned));const label=$('#activityPropLabel');if(label)label.textContent=setting.id==='pizza'?`PIZZA · ${activityProgressName('pizza',earned)}`:setting.id==='milkshake'?`SHAKE · ${activityProgressName('milkshake',earned)}`:'';if(pop){prop.classList.remove('food-pop');void prop.offsetWidth;prop.classList.add('food-pop');setTimeout(()=>prop.classList.remove('food-pop'),620);}}
function foodCorrectReaction(){const setting=game?.setting;if(setting==='pizza'){const lines=['CHEESE!','MORE PIZZA!','I CAN SMELL THE MATHEMATICS.','HURRY, PROFESSOR.','PIZZA PROGRESS!'];say(random(lines),'ping');reactionGlyph(random(['YUM!','PIZZA!','MORE!']),'smug');}else if(setting==='milkshake'){const lines=['MILKSHAKE!','MORE SPRINKLES.','BLEND IT!','I REQUIRE WHIPPED CREAM.','SPELL FASTER. I AM THIRSTY.'];say(random(lines),'ping');reactionGlyph(random(['SLURP!','SHAKE!','YUM!']),'smug');}}
function renderNext(){if(game.index>=game.length){finishGame();return;}game.locked=false;$('#feedback').textContent='';$('#feedback').className='feedback';const focused=pickFocusedDescriptor();const adaptive=focused?null:chooseAdaptiveDescriptor(prefs,{grade:prefs.grade,subject:game.subject,enabledSubjects:prefs.enabledSubjects});const target=focused||adaptive;const difficulty=adaptiveDifficultyFor(prefs,target?.skillId,game.difficulty);const q=generateUniqueQuestion({grade:prefs.grade,subject:target?.subject||game.subject,skill:target?.skill||prefs.skill,difficulty,subjects:prefs.enabledSubjects},game.usedFingerprints);if(adaptive)game.adaptivePicks++;game.current=q;game.questions.push(q);game.usedFingerprints.add(questionFingerprint(q));$('#questionCounter').textContent=`${game.index+1} / ${game.length}`;const sm=subjectMeta(q.subject);$('#subjectPill').innerHTML=`<img class="mini-subject-icon" src="${sm.art}" alt=""><span>${sm.name}</span>`;$('#skillPill').textContent=q.skillName||q.skill.replaceAll('-',' ');$('#questionText').textContent=q.prompt;$('#questionText').classList.toggle('professor-hosted-question',professorHostsQuestion(q));$('#questionText').classList.remove('question-enter');void $('#questionText').offsetWidth;$('#questionText').classList.add('question-enter');setProfessorBattleMode(q);renderQuestionVisual(q);const grid=$('#answerGrid');renderInteraction(q,grid,(choice,button)=>answer(choice,button));if(!professorHostsQuestion(q)){$('#glorpBubble')?.classList.remove('hidden');const bank=subjectNonsense[q.subject]||nonsense;say(random(bank),'ping');}else{$('#glorpBubble')?.classList.add('hidden');setBubble('');}if(Math.random()<.38)performRigPose('smug',760);updateMeters(false);const rig=$('#glorpRig');rig?.classList.add('rig-look-question');setTimeout(()=>rig?.classList.remove('rig-look-question'),420);applyCosmetic();}
function renderQuestionVisual(q){const visual=$('#questionVisual'),passage=$('#passageCard');visual.innerHTML='';visual.classList.add('hidden');passage.classList.add('hidden');passage.textContent='';if(q.visualType==='clock'){visual.classList.remove('hidden');visual.setAttribute('aria-hidden','false');visual.appendChild(buildClock(q.visualData.hour,q.visualData.minute));}else visual.setAttribute('aria-hidden','true');if(q.visualType==='passage'&&q.visualData?.passage){passage.textContent=q.visualData.passage;passage.classList.remove('hidden');}}
function buildClock(hour,minute){const el=document.createElement('div');el.className='analog-clock';el.innerHTML='<span class="clock-dot"></span><span class="hand hour-hand"></span><span class="hand minute-hand"></span>'+[12,3,6,9].map(n=>`<b class="clock-num n${n}">${n}</b>`).join('');el.querySelector('.hour-hand').style.transform=`translateX(-50%) rotate(${(hour%12)*30+minute*.5}deg)`;el.querySelector('.minute-hand').style.transform=`translateX(-50%) rotate(${minute*6}deg)`;return el;}
function trackSubject(q,correct){recordProgressAnswer(prefs,q,correct);game.subjectScores[q.subject]??={correct:0,attempts:0};game.subjectScores[q.subject].attempts++;if(correct)game.subjectScores[q.subject].correct++;}
function answer(choice,button){if(game.locked||paused)return;game.locked=true;const choiceIndex=[...$('#answerGrid').querySelectorAll('.answer')].indexOf(button);lookAtChoice(choiceIndex);audio.sfx('tap',.6);$$('.answer').forEach(b=>b.disabled=true);const correct=isCorrect(choice,game.current),foodMode=game.setting==='pizza'||game.setting==='milkshake';game.recent.push(correct);if(game.recent.length>6)game.recent.shift();trackSubject(game.current,correct);
  if(correct){game.score++;game.streak++;game.bestStreak=Math.max(game.bestStreak,game.streak);if(!foodMode)game.ragePoints+=1;prefs.lifetimeCorrect++;button.classList.add('correct');if(professorHostsQuestion(game.current))professorBattleSay('CORRECT!','good');$('#feedback').textContent=game.mode==='quiz'?'CORRECT! Glorp noticed.':game.setting==='pizza'?'CORRECT! Pizza progress!':game.setting==='milkshake'?'CORRECT! Add it to the blender!':'CORRECT! Glorp rage increases!';$('#feedback').className='feedback good';audio.sfx('correct',.9);haptic(18);screenFlash('good');burst('spark',12);if(foodMode){updateActivityProp(true);setTimeout(()=>{performRigPose(Math.random()<.5?'smug':'fist',820);foodCorrectReaction();},220);}else{const level=rageLevel(game.ragePoints),bank=level>=3?glorpLines.furious:level>=2?glorpLines.angry:glorpLines.correct;const line=random(bank);const pose=level>=3?'head':(['point','fist','shock'][Math.floor(Math.random()*3)]);setTimeout(()=>{performRigPose(pose,900);stageImpact('correct');},100);setTimeout(()=>{say(line,level>=2?'growl':'rage');reactionGlyph(random(['WHAT?!','NO!','HEY!','CHEATER!']),'angry');},260);}
  }else{game.streak=0;if(!foodMode)game.ragePoints=Math.max(0,game.ragePoints-.35);game.missed.push({question:game.current,choice});button.classList.add('wrong');const right=[...$$('.answer')].find(b=>String(b.textContent)===String(game.current.answer));right?.classList.add('correct');if(professorHostsQuestion(game.current))professorBattleSay('WRONG!','bad');const professorCorrection=professorHostsQuestion(game.current)?` Glorp was joking. ${random(glorpLines.professorJokeChecks)}`:'';$('#feedback').textContent=professorHostsQuestion(game.current)?`Correct answer: ${game.current.answer}. ${game.current.explanation}${professorCorrection}`:`Correct answer: ${game.current.answer}`;$('#feedback').className='feedback bad';audio.sfx('wrong',.75);haptic([26,35,26]);screenFlash('bad');setTimeout(()=>{performRigPose(Math.random()<.55?'smug':'point',900);if(!foodMode)stageImpact('wrong');audio.sfx('laugh',.65);},110);setTimeout(()=>{const wrongBank=glorpLines.wrongBySubject?.[game.current.subject]||glorpLines.wrong;say(random(wrongBank),'laugh');reactionGlyph(foodMode?(game.setting==='pizza'?'PIZZA DELAYED!':'NO SHAKE YET!'):'HA!','smug');if(!foodMode)burst('slime',8);},250);}
  game.difficulty=nextDifficulty(game.difficulty,game.recent);const oldLevel=game.lastRageLevel,newLevel=foodMode?0:rageLevel(game.ragePoints);setTimeout(()=>{updateMeters(false);if(!foodMode&&newLevel>oldLevel)setTimeout(()=>levelUpRage(newLevel),140);},390);game.lastRageLevel=newLevel;save();setTimeout(()=>{game.index++;renderNext();},1650);
}
function updateMeters(roundOver){const scorePct=(game?.score||0)/Math.max(1,game?.length||prefs.sessionLength),setting=gameplaySetting(game?.setting);$('#brainPower').textContent=Math.round(scorePct*100);$('#brainFill').style.width=`${scorePct*100}%`;const meterTitle=$('#activityMeterTitle');if(meterTitle)meterTitle.lastChild.textContent=setting.meterTitle;const foodMode=setting.id==='pizza'||setting.id==='milkshake';if(foodMode){const earned=earnedActivityLayers(setting.id,game?.score||0,game?.length||1);$('#rageName').textContent=activityProgressName(setting.id,earned);$('#rageFill').style.width=`${scorePct*100}%`;const stage=$('#glorpStage');['rage-0','rage-1','rage-2','rage-3','rage-4'].forEach(c=>stage.classList.remove(c));stage.classList.add('rage-0');document.documentElement.style.setProperty('--rage','0');audio.setIntensity(Math.min(2,Math.floor(scorePct*3)));updateActivityProp();applyCosmetic();return;}const lvl=rageLevel(game?.ragePoints||0,roundOver,game?.score||0,game?.length||prefs.sessionLength),names=['SMUG','ANNOYED','ANGRY','FURIOUS','MELTDOWN'];$('#rageName').textContent=names[lvl];$('#rageFill').style.width=`${[8,28,52,78,100][lvl]}%`;const stage=$('#glorpStage');['rage-0','rage-1','rage-2','rage-3','rage-4'].forEach(c=>stage.classList.remove(c));stage.classList.add(`rage-${lvl}`);document.documentElement.style.setProperty('--rage',String(lvl));const rig=$('#glorpRig');if(rig)rig.dataset.rage=String(lvl);audio.setIntensity(lvl);applyCosmetic();}
function finishGame(){prefs.rounds++;const foodMode=game.setting==='pizza'||game.setting==='milkshake';if(!foodMode&&game.score>=Math.ceil(game.length*.5))prefs.wins++;if(game.mode==='quiz')prefs.quizzes++;if(game.sessionLabel==='MASTERY PRACTICE')prefs.masteryPractices=(prefs.masteryPractices||0)+1;recordSession(prefs,{grade:prefs.grade,mode:game.mode,subject:game.subject,label:game.sessionLabel,score:game.score,total:game.length,bestStreak:game.bestStreak,adaptivePicks:game.adaptivePicks});save();updateMeters(true);if(game.mode==='quiz'){finishQuiz();return;}const ratio=game.score/game.length,strong=ratio>=.8,glorpWin=ratio<.5;let delay=520;if(foodMode){const prop=$('#activityProp');prop?.classList.add('eating');if(game.setting==='pizza'){say(strong?'OM NOM NOM NOM NOM!':'PIZZA! NOM NOM NOM!','laugh');reactionGlyph('OM NOM!','smug');$('#resultTitle').textContent=strong?'PIZZA MASTERPIECE!':'PIZZA COMPLETE!';$('#resultSubtitle').textContent=strong?'Glorp inhaled the entire pizza and has no regrets.':'You cooked what you earned. Glorp ate it anyway.';}else{say(strong?'SLURRRRP! BRAIN FREEZE!':'SLURP SLURP SLURP!','laugh');reactionGlyph('SLURP!','smug');$('#resultTitle').textContent=strong?'MILKSHAKE MASTERPIECE!':'MILKSHAKE COMPLETE!';$('#resultSubtitle').textContent=strong?'Glorp drank it so fast he achieved brain freeze.':'Glorp considers every milkshake a successful experiment.';}audio.sfx('unlock',.75);delay=1350;}else if(strong){const stage=$('#glorpStage');stage.classList.add('meltdown');rigReaction('meltdown');audio.cutMusic(650);screenFlash('rage');burst('slime',34);burst('ember',18);say('THIS GAME IS CHEATING!','growl');audio.sfx('splat',1);setTimeout(()=>audio.sfx('growl',.7),220);delay=1450;}else if(glorpWin){rigReaction('wrong');say('HAHA! GLORP WINS!','laugh');audio.sfx('laugh',.8);delay=950;}else{rigReaction('rage');say('That question was rigged!','rage');delay=850;}setTimeout(()=>{const r=resultLabel(game.score,game.length);if(!foodMode){$('#resultTitle').textContent=r.title;$('#resultSubtitle').textContent=r.subtitle;}$('#resultScore').textContent=`${game.score} / ${game.length}`;$('#resultStreak').textContent=game.bestStreak;const card=$('#resultCard');card.classList.remove('big-win','mid-win','glorp-win');card.classList.add(strong?'big-win':glorpWin?'glorp-win':'mid-win');show('resultScreen');audio.stopMusic();if(strong&&!foodMode)audio.sfx('unlock',.75);},delay);}
function finishQuiz(){const grade=quizGrade(game.score,game.length),ratio=game.score/game.length;lastQuizMisses=[...game.missed];let delay=650;if(ratio>=.8){rigReaction('meltdown');audio.cutMusic(650);screenFlash('rage');burst('slime',30);say(ratio===1?'THIS GAME IS CHEATING!':'STOP KNOWING THINGS!','growl');audio.sfx('splat',.9);delay=1350;}else if(grade.needsReview){rigReaction('wrong');say('See? Glorp genius!','laugh');delay=850;}else{rigReaction('rage');say('Glorp demands a recount!','rage');delay=850;}setTimeout(()=>{audio.stopMusic();renderQuizReport(grade);show('quizResultScreen');},delay);}
function renderQuizReport(grade){audio.sfx('stamp',.72);audio.playSting(grade.needsReview?'review':'win');const report=$('#quizReportCard');report.classList.remove('grade-reveal');void report.offsetWidth;report.classList.add('grade-reveal');setTimeout(()=>report.classList.remove('grade-reveal'),1000);$('#quizReportGradeLabel').textContent=`${ordinal(prefs.grade).toUpperCase()} GRADE`;$('#letterGrade').textContent=grade.letter;$('#quizLetterSmall').textContent=grade.letter;$('#quizScore').textContent=`${game.score} / ${game.length}`;$('#quizResultSubtitle').textContent=grade.needsReview?'Professor Brainrot has reluctantly scheduled a review.':game.score===game.length?'Glorp is experiencing an A+ emergency.':'Good work. Glorp hates this.';$('#quizGlorpBubble').textContent=game.score===game.length?'A PLUS?!':grade.letter==='A'?'WHO ALLOWED THIS?!':grade.letter==='B'?'B = BRAINROT!':grade.needsReview?'I AM PROFESSOR NOW.':'RECOUNT!';const list=$('#subjectScoreList');list.innerHTML='';Object.entries(game.subjectScores).forEach(([id,s])=>{const m=subjectMeta(id),pct=Math.round(s.correct/s.attempts*100);const row=document.createElement('div');row.innerHTML=`<span><img class="mini-subject-icon" src="${m.art}" alt="">${m.name}</span><b>${s.correct}/${s.attempts}</b><i>${pct}%</i>`;list.appendChild(row);});$('#reviewBtn').classList.toggle('hidden',!grade.needsReview||!lastQuizMisses.length);}

function startReview(){if(!lastQuizMisses.length)return;review={items:lastQuizMisses.slice(0,6),index:0,mastered:0,sourceMisses:lastQuizMisses.map(x=>x.question)};show('reviewScreen');audio.startMusic('professor');audio.sfx('page',.55);professorSay('Ahem. Professor Brainrot will now educate you.','growl');document.querySelector('.professor-rig')?.classList.add('prof-intro','prof-lecture');setTimeout(()=>{document.querySelector('.professor-rig')?.classList.remove('prof-intro','prof-lecture');renderReviewItem();},1100);}
function renderReviewItem(){if(review.index>=review.items.length){prefs.reviews++;save();$('#reviewMastered').textContent=`${review.mastered} / ${review.items.length}`;$('#reviewCompleteText').textContent=review.mastered===review.items.length?'Professor Brainrot is deeply annoyed. You mastered every review question.':'You reviewed the missed skills. A focused retake can lock them in.';const pr=document.querySelector('.professor-rig');pr?.classList.add(review.mastered===review.items.length?'prof-defeat':'prof-think');audio.sfx(review.mastered===review.items.length?'splat':'page',.45);setTimeout(()=>{audio.stopMusic();show('reviewCompleteScreen');audio.sfx('unlock',.7);audio.playSting('win');pr?.classList.remove('prof-defeat','prof-think');},review.mastered===review.items.length?760:420);return;}const item=review.items[review.index],q=item.question,sm=subjectMeta(q.subject),tryQ=generateReviewQuestion(q);review.tryQ=tryQ;$('#reviewProgress').textContent=`Review ${review.index+1} of ${review.items.length}`;$('#reviewSubject').innerHTML=`<img class="mini-subject-icon" src="${sm.art}" alt=""><span>${sm.name.toUpperCase()}</span>`;$('#reviewQuestion').textContent=q.prompt;$('#reviewYourAnswer').textContent=item.choice;$('#reviewCorrectAnswer').textContent=q.answer;$('#reviewExplanation').textContent=q.explanation;const prompt=$('#reviewTryPrompt');prompt.innerHTML='';if(tryQ.visualType==='clock')prompt.appendChild(buildClock(tryQ.visualData.hour,tryQ.visualData.minute));if(tryQ.visualType==='passage'){const p=document.createElement('p');p.className='mini-passage';p.textContent=tryQ.visualData.passage;prompt.appendChild(p);}const h=document.createElement('div');h.className='review-try-question';h.textContent=tryQ.prompt;prompt.appendChild(h);const grid=$('#reviewAnswerGrid');grid.innerHTML='';tryQ.choices.forEach((choice,i)=>{const b=document.createElement('button');b.className='answer';b.dataset.choiceLabel=String.fromCharCode(65+i);b.textContent=choice;b.addEventListener('click',()=>answerReview(choice,b));grid.appendChild(b);});$('#reviewFeedback').textContent='';$('#reviewFeedback').className='feedback';professorSay(tryQ.subject==='spelling'?'Choose the correctly spelled word. No hints from me.':random(glorpLines.professor),'chalk');const pr=document.querySelector('.professor-rig');pr?.classList.remove('prof-think','prof-lecture');void pr?.offsetWidth;pr?.classList.add(Math.random()<.5?'prof-think':'prof-lecture');setTimeout(()=>pr?.classList.remove('prof-think','prof-lecture'),950);}
function answerReview(choice,button){const q=review.tryQ;$('#reviewAnswerGrid').querySelectorAll('button').forEach(b=>b.disabled=true);if(isCorrect(choice,q)){review.mastered++;button.classList.add('correct');$('#reviewFeedback').textContent='MASTERED! Professor Brainrot is offended.';$('#reviewFeedback').className='feedback good';professorSay(random(glorpLines.reviewCorrect),'growl');audio.sfx('correct',.85);haptic(18);audio.sfx('chalk',.35);screenFlash('good');const pr=document.querySelector('.professor-rig');pr?.classList.add('prof-offended','prof-success');setTimeout(()=>pr?.classList.remove('prof-offended','prof-success'),900);}else{button.classList.add('wrong');[...$('#reviewAnswerGrid').querySelectorAll('.answer')].find(b=>String(b.textContent)===String(q.answer))?.classList.add('correct');$('#reviewFeedback').textContent=`Correct answer: ${q.answer}`;$('#reviewFeedback').className='feedback bad';professorSay(random(glorpLines.reviewWrong),'growl');audio.sfx('wrong',.7);haptic([24,32,24]);audio.sfx('page',.35);const pr=document.querySelector('.professor-rig');pr?.classList.add('prof-teach','prof-lecture');setTimeout(()=>pr?.classList.remove('prof-teach','prof-lecture'),950);}setTimeout(()=>{review.index++;renderReviewItem();},1450);}
function startFocusedRetake(){const desc=review?.sourceMisses?.map(q=>({subject:q.subject,skill:q.skill}))||lastQuizMisses.map(x=>({subject:x.question.subject,skill:x.question.skill}));const unique=[];const seen=new Set();for(const d of desc){const k=`${d.subject}:${d.skill}`;if(!seen.has(k)){seen.add(k);unique.push(d);}}startSession('quiz','mixed',{length:Math.max(5,Math.min(10,unique.length*2)),focusDescriptors:unique});}

function applyCosmetic(){const c=cosmetics.find(x=>x.id===prefs.equipped)||cosmetics[0],badge=$('#cosmeticBadge');badge.innerHTML=c.id==='none'?'':(c.art?`<img src="${c.art}" alt="">`:c.icon);badge.dataset.cosmetic=c.id;}
function renderCloset(){const grid=$('#closetGrid');grid.innerHTML='';cosmetics.forEach(c=>{const locked=prefs.wins<c.unlockWins,b=document.createElement('button');b.className=`closet-item ${locked?'locked':''} ${prefs.equipped===c.id?'equipped':''}`;b.disabled=locked;b.innerHTML=`<div class="cosmetic-preview">${locked?'<img class="closet-state-icon" src="assets/ui/nav/lock.svg" alt="Locked">':(c.art?`<img src="${c.art}" alt="">`:c.icon)}${!locked&&prefs.equipped===c.id?'<img class="closet-check" src="assets/ui/nav/check.svg" alt="Equipped">':''}</div><b>${c.name}</b><small>${locked?`Win ${c.unlockWins} rounds`:(prefs.equipped===c.id?'Equipped':'Tap to equip')}</small>`;b.addEventListener('click',()=>{prefs.equipped=c.id;save();audio.sfx('unlock',.7);renderCloset();});grid.appendChild(b);});}
function renderParentSubjects(){const box=$('#parentSubjectToggles');box.innerHTML='';subjects.filter(s=>s.id!=='mixed').forEach(s=>{const label=document.createElement('label');label.className='subject-check';label.innerHTML=`<input type="checkbox" data-subject-toggle="${s.id}" ${prefs.enabledSubjects.includes(s.id)?'checked':''}><span><img class="mini-subject-icon" src="${s.art}" alt="">${s.name}</span>`;box.appendChild(label);});}
function masteryPracticeDescriptors(){
  const grade=String(prefs.grade),recommended=recommendedSkills(prefs,grade,4);
  if(recommended.length)return recommended.map(r=>({subject:r.subject,skill:r.skill,skillId:r.skillId}));
  return skillWeaknesses(prefs,grade,4).map(r=>({subject:r.subject,skill:r.skill,skillId:r.skillId}));
}
function startMasteryPractice(){
  const descriptors=masteryPracticeDescriptors();
  if(!descriptors.length){showToast('Play a few learning rounds first so Professor Brainrot can find weak skills.');return;}
  startSession('battle','mixed',{length:Math.max(5,Math.min(10,descriptors.length*2)),focusDescriptors:descriptors,label:'MASTERY PRACTICE'});
}
function humanizeSkill(skill){return String(skill||'practice').replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase());}
function renderParentDashboard(){
  const grade=$('#parentProgressGrade')?.value||String(prefs.grade),snap=progressSnapshot(prefs,grade),subjectBox=$('#parentSubjectStats'),recent=$('#parentRecentActivity'),recs=$('#parentRecommendations'),skillsBox=$('#parentSkillMastery');
  $('#parentAccuracy').textContent=snap.accuracy==null?'—':`${snap.accuracy}%`;
  $('#parentQuestions').textContent=snap.attempts;
  $('#parentSessions').textContent=snap.sessions.length;
  $('#parentQuizAverage').textContent=snap.quizAverage==null?'—':`${snap.quizAverage}%`;
  $('#parentSkillsTracked').textContent=snap.skillsTracked||0;
  $('#parentSkillsMastered').textContent=snap.skillsMastered||0;
  const entries=subjects.filter(s=>s.id!=='mixed').map(meta=>({meta,stats:snap.subjectStats?.[meta.id]||{correct:0,attempts:0}}));
  subjectBox.innerHTML='';
  entries.forEach(({meta,stats})=>{const accuracy=stats.attempts?Math.round(stats.correct/stats.attempts*100):null,band=progressBand(accuracy,stats.attempts),row=document.createElement('div');row.className=`parent-subject-row ${band.key}`;row.innerHTML=`<span class="parent-subject-name"><img class="mini-subject-icon" src="${meta.art}" alt=""><span><b>${meta.name}</b><small>${stats.attempts||0} questions</small></span></span><span class="parent-progress-meter"><i style="width:${accuracy||0}%"></i></span><strong>${accuracy==null?'—':accuracy+'%'}</strong><em>${band.label}</em>`;subjectBox.appendChild(row);});
  const recommendations=recommendedSkills(prefs,grade,4);
  if(recommendations.length){recs.innerHTML=recommendations.map(r=>{const m=subjectMeta(r.subject);return `<div><img class="mini-subject-icon" src="${m.art}" alt=""><span><b>${m.name}: ${r.skillName||humanizeSkill(r.skill)}</b><small>${r.band.label} · ${r.masteryScore}% mastery · ${r.attempts} attempts</small></span></div>`;}).join('');}
  else{const weaknesses=skillWeaknesses(prefs,grade,3);recs.innerHTML=weaknesses.length?weaknesses.map(w=>{const m=subjectMeta(w.subject);return `<div><img class="mini-subject-icon" src="${m.art}" alt=""><span><b>Practice ${m.name}: ${w.skillName||humanizeSkill(w.skill)}</b><small>${w.accuracy}% across ${w.attempts} attempts</small></span></div>`;}).join(''):'<p class="empty-progress">Complete a few learning rounds and quizzes to build mastery recommendations.</p>';}
  const practiceBtn=$('#practiceWeakSkillsBtn');if(practiceBtn){const available=masteryPracticeDescriptors().length>0;practiceBtn.disabled=!available;practiceBtn.textContent=available?'PRACTICE WEAK SKILLS':'PRACTICE BUILDS AFTER A FEW ROUNDS';}
  const skillRows=masteryRecords(prefs,grade).sort((a,b)=>(b.attempts||0)-(a.attempts||0)||(a.masteryScore||0)-(b.masteryScore||0)).slice(0,8);
  skillsBox.innerHTML='';
  if(skillRows.length){for(const record of skillRows){const band=masteryBand(record),m=subjectMeta(record.subject),row=document.createElement('div');row.className=`parent-skill-row ${band.key}`;row.innerHTML=`<span><img class="mini-subject-icon" src="${m.art}" alt=""><span><b>${record.skillName||humanizeSkill(record.skill)}</b><small>${m.name} · ${record.attempts} attempts</small></span></span><span class="parent-progress-meter"><i style="width:${record.masteryScore||0}%"></i></span><strong>${record.masteryScore||0}%</strong><em>${band.label}</em>`;skillsBox.appendChild(row);}}
  else skillsBox.innerHTML='<p class="empty-progress">Skill mastery begins building as new v0.10 questions are answered.</p>';
  recent.innerHTML='';snap.sessions.slice(0,6).forEach(session=>{const m=subjectMeta(session.subject),row=document.createElement('div'),pct=Math.round(session.score/session.total*100),date=new Date(session.date);row.innerHTML=`<span><b>${session.label||((session.mode==='quiz'?'Quiz':'Battle')+' · '+(session.subject==='mixed'?'Mixed Brain Battle':m.name))}</b><small>${date.toLocaleDateString(undefined,{month:'short',day:'numeric'})} · ${ordinal(session.grade)} Grade${session.adaptivePicks?` · ${session.adaptivePicks} adaptive`:''}</small></span><strong>${session.score}/${session.total}</strong><em>${pct}%</em>`;recent.appendChild(row);});
  if(!snap.sessions.length)recent.innerHTML='<p class="empty-progress">Recent activity will appear here after a completed round.</p>';
  const note=$('#parentProgressNote');if(note)note.textContent=String(grade)==='all'?'Lifetime totals are preserved. Skill mastery and adaptive-learning analytics begin with v0.10.':'Showing grade-specific progress. v0.10 mastery uses recent performance more heavily than older answers.';
}
function loadSettings(){$('#parentGrade').value=prefs.grade;$('#parentProgressGrade').value=String(prefs.grade);$('#sessionLength').value=prefs.sessionLength;$('#skillSelect').value=prefs.skill;$('#soundToggle').checked=prefs.sound;$('#voiceToggle').checked=prefs.voice;$('#musicToggle').checked=prefs.music;$('#hapticsToggle').checked=prefs.haptics;$('#largeTextToggle').checked=prefs.largeText;$('#statRounds').textContent=prefs.rounds;$('#statWins').textContent=prefs.wins;$('#statCorrect').textContent=prefs.lifetimeCorrect;$('#statQuizzes').textContent=prefs.quizzes||0;$('#statReviews').textContent=prefs.reviews||0;$('#statMasteryPractice').textContent=prefs.masteryPractices||0;renderParentSubjects();renderParentDashboard();}
function saveSettings(){prefs.grade=Number($('#parentGrade').value);prefs.sessionLength=Number($('#sessionLength').value);prefs.skill=$('#skillSelect').value;prefs.sound=$('#soundToggle').checked;prefs.voice=$('#voiceToggle').checked;prefs.music=$('#musicToggle').checked;prefs.haptics=$('#hapticsToggle').checked;prefs.largeText=$('#largeTextToggle').checked;applyAccessibilityPrefs();const enabled=$$('[data-subject-toggle]:checked').map(x=>x.dataset.subjectToggle);prefs.enabledSubjects=enabled.length?enabled:[...SUBJECT_KEYS];save();updateHome();audio.stopMusic();show('homeScreen');}

$('#playBtn').addEventListener('click',openGameplayPicker);$('#quizBtn').addEventListener('click',()=>openSubjectPicker('quiz'));$('#gradeBtn').addEventListener('click',()=>show('gradeScreen'));$('#closetBtn').addEventListener('click',()=>{renderCloset();show('closetScreen');});$('#parentBtn').addEventListener('click',()=>{loadSettings();show('parentScreen');});
$('#homeGradeQuickBtn').addEventListener('click',()=>show('gradeScreen'));$('#homeSubjectBtn').addEventListener('click',openGameplayPicker);$('#reviewShortcutBtn').addEventListener('click',()=>{if(lastQuizMisses.length)startReview();else startMasteryPractice();});
$('#navHomeBtn').addEventListener('click',()=>{audio.stopMusic();updateHome();show('homeScreen');});$('#navPlayBtn').addEventListener('click',openGameplayPicker);$('#navQuizBtn').addEventListener('click',()=>openSubjectPicker('quiz'));$('#navClosetBtn').addEventListener('click',()=>{renderCloset();show('closetScreen');});$('#navParentBtn').addEventListener('click',()=>{loadSettings();show('parentScreen');});
$$('[data-gameplay]').forEach(b=>b.addEventListener('click',()=>launchGameplaySetting(b.dataset.gameplay)));$('.activity-back')?.addEventListener('click',()=>show('homeScreen'));
$$('.back-btn').forEach(b=>b.addEventListener('click',()=>{audio.stopMusic();updateHome();show('homeScreen');}));$('.subject-back').addEventListener('click',()=>show('homeScreen'));$$('.grade-card').forEach(b=>b.addEventListener('click',()=>{prefs.grade=Number(b.dataset.grade);save();updateHome();show('homeScreen');}));
$('#rematchBtn').addEventListener('click',()=>startSession('battle',game.subject,{setting:game.setting,label:game.sessionLabel}));$('#resultHomeBtn').addEventListener('click',()=>{audio.stopMusic();updateHome();show('homeScreen');});$('#quizRematchBtn').addEventListener('click',()=>startSession('quiz',game.subject));$('#quizHomeBtn').addEventListener('click',()=>{updateHome();show('homeScreen');});$('#reviewBtn').addEventListener('click',startReview);$('#practiceWeakSkillsBtn').addEventListener('click',startMasteryPractice);$('#reviewExitBtn').addEventListener('click',()=>show('quizResultScreen'));$('#reviewHomeBtn').addEventListener('click',()=>{updateHome();show('homeScreen');});$('#focusedRetakeBtn').addEventListener('click',startFocusedRetake);$('#saveSettingsBtn').addEventListener('click',saveSettings);$('#parentProgressGrade').addEventListener('change',renderParentDashboard);
$('#pauseBtn').addEventListener('click',()=>{paused=true;$('#pauseOverlay').classList.remove('hidden');audio.pause();});$('#resumeBtn').addEventListener('click',()=>{paused=false;$('#pauseOverlay').classList.add('hidden');audio.resume();});$('#quitBtn').addEventListener('click',()=>{paused=false;$('#pauseOverlay').classList.add('hidden');audio.stopVoice();audio.stopMusic();updateHome();show('homeScreen');});
$$('.btn,.icon-btn,.grade-card,.quick-tile,.status-card,.dock-item,.premium-chip').forEach(b=>b.addEventListener('pointerdown',()=>audio.sfx('tap',.28)));
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
window.addEventListener('load',()=>{const splash=$('#bootSplash');setTimeout(()=>{splash?.classList.add('done');setTimeout(()=>splash?.remove(),560);},780);});
document.documentElement.dataset.build='0.14.2';applyAccessibilityPrefs();updateHome();applyCosmetic();save();
